// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuwYlpetv-LSwVbPvMQ3OQ_A8S9HIUWw',
    appId: '1:185672794875:web:71a8bd9c5a4c19f63b665e',
    messagingSenderId: '185672794875',
    projectId: 'ecopilot-test-115f0',
    authDomain: 'ecopilot-test-115f0.firebaseapp.com',
    storageBucket: 'ecopilot-test-115f0.firebasestorage.app',
    measurementId: 'G-2KLF725PGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdRtUjFNR4AX6xrw5mM0Byt_dLA12eTE',
    appId: '1:185672794875:android:9e9ee377c26c3aa93b665e',
    messagingSenderId: '185672794875',
    projectId: 'ecopilot-test-115f0',
    storageBucket: 'ecopilot-test-115f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOO10lS2DITrBZtffWfoTr9a1ee-PxCAE',
    appId: '1:185672794875:ios:d61fda55b8503d003b665e',
    messagingSenderId: '185672794875',
    projectId: 'ecopilot-test-115f0',
    storageBucket: 'ecopilot-test-115f0.firebasestorage.app',
    iosBundleId: 'com.example.ecopilotTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOO10lS2DITrBZtffWfoTr9a1ee-PxCAE',
    appId: '1:185672794875:ios:d61fda55b8503d003b665e',
    messagingSenderId: '185672794875',
    projectId: 'ecopilot-test-115f0',
    storageBucket: 'ecopilot-test-115f0.firebasestorage.app',
    iosBundleId: 'com.example.ecopilotTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyuwYlpetv-LSwVbPvMQ3OQ_A8S9HIUWw',
    appId: '1:185672794875:web:f5155f985778a5823b665e',
    messagingSenderId: '185672794875',
    projectId: 'ecopilot-test-115f0',
    authDomain: 'ecopilot-test-115f0.firebaseapp.com',
    storageBucket: 'ecopilot-test-115f0.firebasestorage.app',
    measurementId: 'G-LQJ840RQ7Z',
  );
}
